name: dataviz
channels:
  - defaults
  - anaconda
dependencies:
  - pip=23.2.1
  - python=3.11.5
  - pandas=2.2.1
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=1.23.4
  - jupyter_server_fileid=0.9.0
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.4
  - jupyterlab=3.6.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.22.0
  - jupyterlab_widgets=3.0.5
  - pip:
      - jupyterthemes==0.20.0
      - missingno==0.5.2